// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using toimi.tools.muistutin.Data;

#nullable disable

namespace toimi.tools.muistutin.Migrations
{
    [DbContext(typeof(MuistutinDbContext))]
    [Migration("20260321090151_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("toimi.tools.muistutin.Data.CompletedOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("OccurrenceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurrence_utc");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uuid")
                        .HasColumnName("reminder_id");

                    b.HasKey("Id")
                        .HasName("pk_completed_occurrences");

                    b.HasIndex("ReminderId", "OccurrenceUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_completed_occurrences_reminder_id_occurrence_utc");

                    b.ToTable("completed_occurrences", (string)null);
                });

            modelBuilder.Entity("toimi.tools.muistutin.Data.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("DateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DisplayEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("display_end_utc");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text")
                        .HasColumnName("recurrence_rule");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_reminders");

                    b.HasIndex("DateTimeUtc", "DisplayEndUtc")
                        .HasDatabaseName("idx_reminders_active_range")
                        .HasFilter("NOT is_completed");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("toimi.tools.muistutin.Data.CompletedOccurrence", b =>
                {
                    b.HasOne("toimi.tools.muistutin.Data.Reminder", "Reminder")
                        .WithMany("CompletedOccurrences")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_completed_occurrences_reminders_reminder_id");

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("toimi.tools.muistutin.Data.Reminder", b =>
                {
                    b.Navigation("CompletedOccurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
