// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using toimi.tools.tietue.Data;

#nullable disable

namespace toimi.tools.tietue.Migrations
{
    [DbContext(typeof(TietueDbContext))]
    [Migration("20260617042511_AddUniqueKeys")]
    partial class AddUniqueKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("toimi.tools.tietue.Data.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_entities");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_entities_type");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("toimi.tools.tietue.Data.EntityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurrenceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurrence_utc");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_entity_events");

                    b.HasIndex("EntityId", "OccurrenceUtc", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_entity_events_entity_id_occurrence_utc_kind");

                    b.ToTable("entity_events", (string)null);
                });

            modelBuilder.Entity("toimi.tools.tietue.Data.Trigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("HandlerConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("handler_config");

                    b.Property<string>("HandlerKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handler_kind");

                    b.Property<DateTimeOffset?>("LastFiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fired_at");

                    b.Property<DateTimeOffset?>("NextFireAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_fire_at");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("schedule");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_triggers");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_triggers_entity_id");

                    b.HasIndex("Enabled", "NextFireAt")
                        .HasDatabaseName("ix_triggers_enabled_next_fire_at");

                    b.ToTable("triggers", (string)null);
                });

            modelBuilder.Entity("toimi.tools.tietue.Data.TypeDefinition", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Behaviors")
                        .HasColumnType("jsonb")
                        .HasColumnName("behaviors");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DefaultTriggers")
                        .HasColumnType("jsonb")
                        .HasColumnName("default_triggers");

                    b.Property<string>("JsonSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json_schema");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Name")
                        .HasName("pk_type_definitions");

                    b.ToTable("type_definitions", (string)null);
                });

            modelBuilder.Entity("toimi.tools.tietue.Data.UniqueKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_unique_keys");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_unique_keys_entity_id");

                    b.HasIndex("Type", "Field", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_unique_keys_type_field_value");

                    b.ToTable("unique_keys", (string)null);
                });

            modelBuilder.Entity("toimi.tools.tietue.Data.EntityEvent", b =>
                {
                    b.HasOne("toimi.tools.tietue.Data.Entity", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entity_events_entities_entity_id");
                });

            modelBuilder.Entity("toimi.tools.tietue.Data.Trigger", b =>
                {
                    b.HasOne("toimi.tools.tietue.Data.Entity", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_triggers_entities_entity_id");
                });

            modelBuilder.Entity("toimi.tools.tietue.Data.UniqueKey", b =>
                {
                    b.HasOne("toimi.tools.tietue.Data.Entity", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unique_keys_entities_entity_id");
                });
#pragma warning restore 612, 618
        }
    }
}
