apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    purpose: application-services
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    purpose: databases
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    purpose: cluster-infrastructure
