#!/usr/bin/env bash
# Generates config.env and the per-overlay secret files from the single root
# toimi.env, so the postgres password and admin credential are defined ONCE.
# Called by dev-setup.sh / server-setup.sh / deploy.sh before they read config.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

ENV="${1:?Usage: render-config.sh <dev|server>}"
case "$ENV" in
  dev | server) ;;
  *) echo "ERROR: env must be 'dev' or 'server', got '$ENV'" >&2; exit 1 ;;
esac

SRC="$ROOT_DIR/toimi.env"
if [ ! -f "$SRC" ]; then
  echo "ERROR: $SRC not found. Copy it: cp toimi.env.example toimi.env" >&2
  exit 1
fi

# Read toimi.env literally — values (passwords, keys) may contain $, backticks,
# spaces, etc. and must NOT be evaluated by the shell (the old per-overlay
# secrets.env files were read literally by kustomize; keep that semantics).
while IFS='=' read -r _key _val || [ -n "$_key" ]; do
  case "$_key" in
    '' | '#'*) continue ;;   # skip blanks and comment lines
  esac
  _key="${_key%"${_key##*[![:space:]]}"}"   # rtrim key
  _key="${_key#"${_key%%[![:space:]]*}"}"   # ltrim key
  # strip one pair of surrounding quotes from the value if present
  case "$_val" in
    \"*\") _val="${_val#\"}"; _val="${_val%\"}" ;;
    \'*\') _val="${_val#\'}"; _val="${_val%\'}" ;;
  esac
  printf -v "$_key" '%s' "$_val"
done < "$SRC"

: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD missing from toimi.env}"

# The single OPENAI_MODEL was split into fast/smart tiers; fail loudly so an
# un-migrated toimi.env cannot silently deploy pods missing their model config.
if [ -n "${OPENAI_MODEL:-}" ]; then
  echo "ERROR: OPENAI_MODEL is no longer used. Replace it in toimi.env with OPENAI_MODEL_FAST" >&2
  echo "       (+ optional OPENAI_MODEL_SMART and the OPENAI_PRICE_* pairs — see toimi.env.example)." >&2
  exit 1
fi
: "${OPENAI_MODEL_FAST:?OPENAI_MODEL_FAST missing from toimi.env (see toimi.env.example)}"

# Optional tier settings default here so the rendered env vars are never empty
# where the .NET config binder expects a number.
OPENAI_MODEL_SMART="${OPENAI_MODEL_SMART:-}"
OPENAI_PRICE_FAST_INPUT_PER_1M="${OPENAI_PRICE_FAST_INPUT_PER_1M:-2.50}"
OPENAI_PRICE_FAST_OUTPUT_PER_1M="${OPENAI_PRICE_FAST_OUTPUT_PER_1M:-10.00}"
OPENAI_PRICE_SMART_INPUT_PER_1M="${OPENAI_PRICE_SMART_INPUT_PER_1M:-2.50}"
OPENAI_PRICE_SMART_OUTPUT_PER_1M="${OPENAI_PRICE_SMART_OUTPUT_PER_1M:-10.00}"
if [ "$ENV" = "server" ]; then
  : "${ADMIN_USER:?ADMIN_USER missing from toimi.env}"
  : "${ADMIN_PASSWORD:?ADMIN_PASSWORD missing from toimi.env}"
fi

GEN_HEADER="# GENERATED by scripts/render-config.sh from toimi.env — DO NOT EDIT."

# --- config.env (non-secret vars sourced by the setup/deploy scripts) ---
cat > "$ROOT_DIR/config.env" <<EOF
$GEN_HEADER
TOIMI_HOST=${TOIMI_HOST}
ADMINER_HOST=${ADMINER_HOST}
QDRANT_HOST=${QDRANT_HOST}
IMAGE_REGISTRY=${IMAGE_REGISTRY}
HOMEASSISTANT_BASE_URL=${HOMEASSISTANT_BASE_URL}
OPENAI_MODEL_FAST=${OPENAI_MODEL_FAST}
EOF

# --- App secrets (toimi-secrets secretGenerator) ---
conn() { echo "Host=postgresql.data.svc.cluster.local;Port=5432;Database=$1;Username=postgres;Password=${POSTGRES_PASSWORD}"; }
APP_SECRETS="$ROOT_DIR/k8s/overlays/$ENV/secrets.env"
mkdir -p "$(dirname "$APP_SECRETS")"
# The smart model (may be empty) and the price numbers ride in toimi-secrets
# instead of envsubst-ed manifest env values: kustomize re-serializes manifests
# and strips quotes, so a numeric or empty substitution would turn a k8s env
# `value:` into a YAML number/null and the apply would be rejected. Secret
# values are always strings.
cat > "$APP_SECRETS" <<EOF
$GEN_HEADER
openai-api-key=${OPENAI_API_KEY}
openai-model-smart=${OPENAI_MODEL_SMART}
openai-price-fast-input-per-1m=${OPENAI_PRICE_FAST_INPUT_PER_1M}
openai-price-fast-output-per-1m=${OPENAI_PRICE_FAST_OUTPUT_PER_1M}
openai-price-smart-input-per-1m=${OPENAI_PRICE_SMART_INPUT_PER_1M}
openai-price-smart-output-per-1m=${OPENAI_PRICE_SMART_OUTPUT_PER_1M}
ha-bearer-token=${HA_BEARER_TOKEN}
toimi-connection-string=$(conn toimi)
ruutu-connection-string=$(conn ruutu)
tietue-connection-string=$(conn tietue)
ntfy-base-url=${NTFY_BASE_URL}
ntfy-topic=${NTFY_TOPIC}
ntfy-username=${NTFY_USERNAME}
ntfy-password=${NTFY_PASSWORD}
EOF

# --- Infra secret (postgres-password; read by the setup scripts' grep) ---
INFRA_SECRETS="$ROOT_DIR/infrastructure/overlays/$ENV/secrets.env"
mkdir -p "$(dirname "$INFRA_SECRETS")"
cat > "$INFRA_SECRETS" <<EOF
$GEN_HEADER
postgres-password=${POSTGRES_PASSWORD}
EOF

# --- Admin basic-auth (server only; both overlays share the same htpasswd) ---
if [ "$ENV" = "server" ]; then
  K8S_AUTH="$ROOT_DIR/k8s/overlays/server/admin-auth.env"
  INFRA_AUTH="$ROOT_DIR/infrastructure/overlays/server/admin-auth.env"

  # bcrypt salt is random, so regenerate only when absent (stable across deploys,
  # no docker/htpasswd needed on every deploy). Rotate = delete these + re-run.
  if [ ! -f "$K8S_AUTH" ] || [ ! -f "$INFRA_AUTH" ]; then
    if command -v htpasswd >/dev/null 2>&1; then
      LINE="$(htpasswd -nbB "$ADMIN_USER" "$ADMIN_PASSWORD")"
    elif command -v docker >/dev/null 2>&1; then
      LINE="$(docker run --rm httpd:2.4-alpine htpasswd -nbB "$ADMIN_USER" "$ADMIN_PASSWORD")"
    else
      echo "ERROR: need 'htpasswd' (apache2-utils) or 'docker' to generate admin auth" >&2
      exit 1
    fi
    printf '%s\nusers=%s\n' "$GEN_HEADER" "$LINE" > "$K8S_AUTH"
    printf '%s\nusers=%s\n' "$GEN_HEADER" "$LINE" > "$INFRA_AUTH"
    echo "Generated admin-auth for user '$ADMIN_USER'."
  fi
fi

echo "Rendered config for '$ENV' from toimi.env."
