// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using toimi.tools.ruutu.Data;

#nullable disable

namespace toimi.tools.ruutu.Data.Migrations
{
    [DbContext(typeof(RuutuDbContext))]
    [Migration("20260604063852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("toimi.tools.ruutu.Data.Entities.Display", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrentData")
                        .HasColumnType("jsonb")
                        .HasColumnName("current_data");

                    b.Property<DateTimeOffset?>("CurrentPushedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_pushed_at");

                    b.Property<string>("CurrentTemplate")
                        .HasColumnType("text")
                        .HasColumnName("current_template");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<string>("IdleData")
                        .HasColumnType("jsonb")
                        .HasColumnName("idle_data");

                    b.Property<string>("IdleTemplate")
                        .HasColumnType("text")
                        .HasColumnName("idle_template");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("LastUserAgent")
                        .HasColumnType("text")
                        .HasColumnName("last_user_agent");

                    b.Property<string>("Orientation")
                        .HasColumnType("text")
                        .HasColumnName("orientation");

                    b.Property<string>("OverlayStack")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("overlay_stack");

                    b.Property<string>("Tier")
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.Property<bool>("TierOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("tier_override");

                    b.Property<int?>("ViewportHeight")
                        .HasColumnType("integer")
                        .HasColumnName("viewport_height");

                    b.Property<int?>("ViewportWidth")
                        .HasColumnType("integer")
                        .HasColumnName("viewport_width");

                    b.HasKey("Id")
                        .HasName("pk_displays");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_displays_identifier");

                    b.ToTable("displays", (string)null);
                });

            modelBuilder.Entity("toimi.tools.ruutu.Data.Entities.DisplayEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayId")
                        .HasColumnType("integer")
                        .HasColumnName("display_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Target")
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<string>("Value")
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_display_events");

                    b.HasIndex("DisplayId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_display_events_display_created");

                    b.ToTable("display_events", (string)null);
                });

            modelBuilder.Entity("toimi.tools.ruutu.Data.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsSeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_seeded");

                    b.Property<string>("LegacyHtml")
                        .HasColumnType("text")
                        .HasColumnName("legacy_html");

                    b.Property<string>("ModernHtml")
                        .HasColumnType("text")
                        .HasColumnName("modern_html");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("schema_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_templates_name");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("toimi.tools.ruutu.Data.Entities.DisplayEvent", b =>
                {
                    b.HasOne("toimi.tools.ruutu.Data.Entities.Display", "Display")
                        .WithMany("Events")
                        .HasForeignKey("DisplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_display_events_displays_display_id");

                    b.Navigation("Display");
                });

            modelBuilder.Entity("toimi.tools.ruutu.Data.Entities.Display", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
