apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

secretGenerator:
  - name: toimi-secrets
    namespace: apps
    envs:
      - secrets.env
    options:
      disableNameSuffixHash: true
